### ISSUE TITLE
Remove the required field from the schema for ruletypes that can automatically guess the default branch for a repo.

### ISSUE THREAD

**Issue by rdimitrov** [mindersec/minder-rules-and-profiles#178]

**Comment by JAORMX** [comment]
This is a good idea. Let's make sure that the upgrade works with `minder ruletype apply`

**Comment by peppescg** [comment]
let me add the slack [thread](https://stacklok.slack.com/archives/C074DPALUBW/p1728545955951269) for better context

**Comment by ethomson** [comment]
I didn't do an _apply_ over an existing configuration, but I did do an apply from an empty setup.

**Comment by rdimitrov** [comment]
@ethomson - I'll give it a test before we close this 👍
